[package]
name = "not-br-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "not-br-cli"
path = "src/main.rs"

[dependencies]
not-br-lib = { path = "../not-br-lib" }
clap = { version = "3.2.8" }